### ISSUE TITLE
Lost input

### ISSUE THREAD

**Issue by Elem8100** [KittyCoat/MonoGame.Forms#42]
keyboard input  doesn’t work when mouse out outside the form. Any solution?

**Comment by KittyCoat** [comment]
Yes, look at the Wiki: https://github.com/KittyCoat/MonoGame.Forms/wiki/F1FF7F99

**Comment by Elem8100** [comment]
Thanks, Didn't notice that.

**Comment by BlizzCrafter** [comment]
This is the new link to the wiki: https://github.com/BlizzCrafter/MonoGame.Forms/wiki

BTW: The [README.md](https://github.com/BlizzCrafter/MonoGame.Forms/blob/master/README.md) contains all the updated links.

**Comment by daxnet** [comment]
@BlizzCrafter Thank you!
